# Generated by Django 5.2.7 on 2025-11-14 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wayline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wayline_id', models.CharField(max_length=50, unique=True, verbose_name='航线ID')),
                ('name', models.CharField(max_length=100, verbose_name='航线名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='航线描述')),
                ('waypoints', models.JSONField(blank=True, null=True, verbose_name='航点数据')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='航线长度(米)')),
                ('estimated_duration', models.IntegerField(blank=True, null=True, verbose_name='预计飞行时间(秒)')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '激活'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=10, verbose_name='航线状态')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '航线信息',
                'verbose_name_plural': '航线信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlarmCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类型代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='telemetry_app.alarmcategory', verbose_name='父类型')),
            ],
            options={
                'verbose_name': '告警类型',
                'verbose_name_plural': '告警类型',
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('role', models.CharField(default='user', max_length=20, verbose_name='角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('content', models.TextField(verbose_name='告警通用描述')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='告警图片链接')),
                ('specific_data', models.JSONField(blank=True, null=True, verbose_name='特定详情')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('IGNORED', '已忽略')], default='PENDING', max_length=10, verbose_name='完成状况')),
                ('handler', models.CharField(blank=True, max_length=50, null=True, verbose_name='处理人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='telemetry_app.alarmcategory', verbose_name='告警类型')),
                ('wayline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='telemetry_app.wayline', verbose_name='关联航线')),
            ],
            options={
                'verbose_name': '告警信息',
                'verbose_name_plural': '告警信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
