# Generated by Django 5.2.7 on 2025-11-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverUrl', models.CharField(max_length=255, verbose_name='服务器地址')),
                ('wssUrl', models.CharField(max_length=255, verbose_name='WSS 地址')),
                ('hostUrl', models.CharField(max_length=255, verbose_name='Host 地址')),
                ('prjId', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目ID')),
                ('projectToken', models.CharField(max_length=255, verbose_name='组织密钥')),
                ('userId', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户ID')),
                ('workspaceId', models.CharField(blank=True, max_length=255, null=True, verbose_name='工作区/组织ID')),
                ('fh2_project_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='兼容字段-项目ID')),
                ('extra_params', models.JSONField(blank=True, null=True, verbose_name='附加参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '组件公共参数',
                'verbose_name_plural': '组件公共参数',
            },
        ),
    ]
