# Generated by Django 5.2.8 on 2025-11-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0002_componentconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentconfig',
            name='hostUrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Host 地址'),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='projectToken',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='组织密钥'),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='serverUrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='服务器地址'),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='wssUrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WSS 地址'),
        ),
    ]
