# Generated by Django 5.2.8 on 2025-11-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0003_alter_componentconfig_hosturl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaylineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片链接')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('alarm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wayline_images', to='telemetry_app.alarm', verbose_name='关联告警')),
                ('wayline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='telemetry_app.wayline', verbose_name='关联航线')),
            ],
            options={
                'verbose_name': '航线图片',
                'verbose_name_plural': '航线图片',
                'ordering': ['-created_at'],
            },
        ),
    ]
