# Generated by Django 5.2.8 on 2025-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0004_waylineimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='媒体文件夹路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '媒体文件夹配置',
                'verbose_name_plural': '媒体文件夹配置',
            },
        ),
    ]
