# Generated by Django 5.2.8 on 2025-12-09 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0005_mediafolderconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='外部任务ID（FH2等）')),
                ('bucket', models.CharField(default='dji', max_length=100, verbose_name='桶名称')),
                ('prefix_list', models.JSONField(verbose_name='MinIO前缀列表')),
                ('started_at', models.DateTimeField(verbose_name='任务开始时间')),
                ('finished_at', models.DateTimeField(verbose_name='任务结束时间')),
                ('expire_at', models.DateTimeField(verbose_name='过期时间')),
                ('detect_status', models.CharField(choices=[('pending', '待检测'), ('processing', '检测中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='检测状态')),
                ('is_cleaned', models.BooleanField(default=False, verbose_name='媒体是否已清理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('wayline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspect_tasks', to='telemetry_app.wayline', verbose_name='关联航线')),
            ],
            options={
                'verbose_name': '巡检任务',
                'verbose_name_plural': '巡检任务',
            },
        ),
    ]
