# Generated by Django 5.2.8 on 2025-12-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0006_inspecttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecttask',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='inspecttask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='inspecttask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务开始时间'),
        ),
    ]
