# Generated by Django 5.2.8 on 2025-12-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0007_alter_inspecttask_expire_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecttask',
            name='detect_type',
            field=models.CharField(choices=[('rail', '轨道'), ('insulator', '绝缘子'), ('bridge', '桥梁'), ('catenary', '接触网')], default='rail', max_length=20, verbose_name='检测类型'),
        ),
    ]
