# Generated by Django 5.2.8 on 2025-12-11 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0008_inspecttask_detect_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wayline',
            name='detect_type',
            field=models.CharField(choices=[('rail', '轨道'), ('insulator', '绝缘子'), ('bridge', '桥梁'), ('catenary', '接触网')], default='rail', max_length=20, verbose_name='默认检测类型'),
        ),
        migrations.CreateModel(
            name='InspectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=512, verbose_name='MinIO对象Key')),
                ('detect_status', models.CharField(choices=[('pending', '待检测'), ('processing', '检测中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='检测状态')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='检测结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inspect_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='telemetry_app.inspecttask', verbose_name='所属巡检任务')),
                ('wayline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telemetry_app.wayline', verbose_name='关联航线')),
            ],
            options={
                'verbose_name': '巡检图片',
                'verbose_name_plural': '巡检图片',
            },
        ),
    ]
