# Generated by Django 5.2.8 on 2025-12-11 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0009_wayline_detect_type_inspectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmcategory',
            options={'verbose_name': '告警类型/检测配置', 'verbose_name_plural': '告警类型/检测配置'},
        ),
        migrations.AddField(
            model_name='alarmcategory',
            name='match_keyword',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MinIO匹配关键字 (配置用)'),
        ),
        migrations.AddField(
            model_name='alarmcategory',
            name='wayline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_categories', to='telemetry_app.wayline', verbose_name='绑定航线 (配置用)'),
        ),
        migrations.AlterField(
            model_name='alarmcategory',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='类型代码/算法标识'),
        ),
        migrations.CreateModel(
            name='WaylineMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_keyword', models.CharField(max_length=100, unique=True, verbose_name='文件夹关键字')),
                ('detect_type', models.CharField(choices=[('rail', '轨道'), ('insulator', '绝缘子'), ('bridge', '桥梁'), ('catenary', '接触网')], default='rail', max_length=20, verbose_name='检测类型')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wayline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_app.wayline', verbose_name='对应航线')),
            ],
            options={
                'verbose_name': '自动映射配置',
                'verbose_name_plural': '自动映射配置',
            },
        ),
    ]
