# Generated by Django 5.2.8 on 2025-12-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0010_alter_alarmcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mediafolderconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='waylineimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='inspecttask',
            name='detect_type',
        ),
        migrations.AddField(
            model_name='inspecttask',
            name='detect_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telemetry_app.alarmcategory', verbose_name='检测类型(配置)'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='specific_data',
            field=models.JSONField(blank=True, null=True, verbose_name='特定详情(算法结果)'),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='extra_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='fh2_project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='hostUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='prjId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='projectToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='serverUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='userId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='workspaceId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='wssUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspecttask',
            name='external_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='外部任务ID'),
        ),
        migrations.AlterField(
            model_name='mediafolderconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mediafolderconfig',
            name='folder_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mediafolderconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waylineimage',
            name='alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wayline_images', to='telemetry_app.alarm'),
        ),
        migrations.AlterField(
            model_name='waylineimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waylineimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waylineimage',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waylineimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='waylineimage',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='waylineimage',
            name='wayline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='telemetry_app.wayline'),
        ),
        migrations.DeleteModel(
            name='WaylineMapping',
        ),
    ]
