# Generated by Django 5.2.8 on 2025-12-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0011_alter_componentconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='source_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_detail', to='telemetry_app.inspectimage', verbose_name='原始底图引用'),
        ),
    ]
