# Generated by Django 5.2.8 on 2025-12-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0012_alarm_source_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecttask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='telemetry_app.inspecttask', verbose_name='所属父任务'),
        ),
    ]
