# Generated by Django 5.2.9 on 2026-01-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0026_merge_20260115_0511"),
    ]

    operations = [
        migrations.AddField(
            model_name="flighttaskinfo",
            name="is_protected_area",
            field=models.BooleanField(default=False, verbose_name="是否为保护区任务"),
        ),
    ]
