# Generated by Django 5.2.9 on 2026-01-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0027_flighttaskinfo_is_protected_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="flight_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alarms",
                to="telemetry_app.flighttaskinfo",
                verbose_name="关联飞行任务",
            ),
        ),
    ]
