# Generated by Django 5.2.9 on 2026-01-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0028_alarm_flight_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(max_length=1000, verbose_name="存疑图片路径(URL)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("CONFIRMED", "已确认误报"),
                            ("IGNORED", "已忽略/并非误报"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注/原因")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上报时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "alarm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspicious_reports",
                        to="telemetry_app.alarm",
                        verbose_name="关联告警",
                    ),
                ),
                (
                    "inspect_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspicious_reports",
                        to="telemetry_app.inspectimage",
                        verbose_name="关联原始巡检图",
                    ),
                ),
            ],
            options={
                "verbose_name": "存疑/误报图片",
                "verbose_name_plural": "存疑/误报图片",
                "ordering": ["-created_at"],
            },
        ),
    ]
