# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0029_suspiciousimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmDashboardStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[("detect_type", "告警统计"), ("handle_rate", "巡检故障处理率")],
                        max_length=20,
                        verbose_name="统计类型",
                    ),
                ),
                (
                    "range_days",
                    models.PositiveIntegerField(default=30, verbose_name="统计范围(天)"),
                ),
                ("total", models.IntegerField(default=0, verbose_name="总数")),
                ("series", models.JSONField(default=list, verbose_name="序列数据")),
                ("window_start", models.DateTimeField(verbose_name="统计窗口开始")),
                ("window_end", models.DateTimeField(verbose_name="统计窗口结束")),
                ("computed_at", models.DateTimeField(auto_now=True, verbose_name="计算时间")),
            ],
            options={
                "verbose_name": "告警看板统计缓存",
                "verbose_name_plural": "告警看板统计缓存",
                "ordering": ["-computed_at"],
                "unique_together": {("metric", "range_days")},
            },
        ),
    ]

