# Generated by Django 5.2.9 on 2026-02-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0029_suspiciousimage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inspectimage",
            index=models.Index(
                fields=["inspect_task", "created_at"],
                name="telemetry_a_inspect_84da66_idx",
            ),
        ),
    ]
