# Generated by Django 5.2.8 on 2026-02-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0030_alarm_dashboard_stats'),
        ('telemetry_app', '0030_inspectimage_telemetry_a_inspect_84da66_idx'),
    ]

    operations = [
    ]
