# Generated by Django 5.2.9 on 2026-02-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0032_inspectimage_task_status_and_objkey_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectimage",
            name="geo_method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="坐标来源方法"
            ),
        ),
        migrations.AddField(
            model_name="inspectimage",
            name="high",
            field=models.FloatField(blank=True, null=True, verbose_name="高度（米）"),
        ),
        migrations.AddField(
            model_name="inspectimage",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                verbose_name="纬度",
            ),
        ),
        migrations.AddField(
            model_name="inspectimage",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                verbose_name="经度",
            ),
        ),
    ]
