# Generated by Django 5.2.8 on 2026-02-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry_app", "0032_flighttaskinfo_flight_stats"),
        ("telemetry_app", "0033_inspectimage_geo_method_inspectimage_high_and_more"),
    ]

    operations = []
