# Generated by Django 5.2.8 on 2026-02-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry_app", "0034_merge_20260212_1832"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightStatsSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_sn",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="无人机SN",
                    ),
                ),
                (
                    "task_uuid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="关联任务UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="是否在飞行会话中"),
                ),
                (
                    "flight_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="飞行开始时间"
                    ),
                ),
                (
                    "last_position_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后位置时间"
                    ),
                ),
                (
                    "last_latitude",
                    models.FloatField(blank=True, null=True, verbose_name="最后纬度"),
                ),
                (
                    "last_longitude",
                    models.FloatField(blank=True, null=True, verbose_name="最后经度"),
                ),
                (
                    "last_altitude",
                    models.FloatField(blank=True, null=True, verbose_name="最后高度"),
                ),
                (
                    "distance_km",
                    models.FloatField(default=0.0, verbose_name="累计飞行里程(km)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "飞行统计会话",
                "verbose_name_plural": "飞行统计会话",
                "ordering": ["-updated_at"],
            },
        ),
    ]
