# Generated by Django 5.2.8 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry_app", "0035_flightstatssession"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmDashboardCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_days", models.PositiveIntegerField(unique=True, verbose_name="统计范围(天)")),
                ("dashboard_data", models.JSONField(default=dict, verbose_name="大屏缓存JSON")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "告警大屏聚合缓存",
                "verbose_name_plural": "告警大屏聚合缓存",
                "ordering": ["-updated_at"],
            },
        ),
    ]
