# Generated by Django 5.2.7 on 2026-03-13 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0036_alarm_dashboard_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="finding_id",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="算法异常ID"
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="level1_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="一级类型编码"
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="level2_code",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="二级类型编码"
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="level3_code",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="三级类型编码"
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="score",
            field=models.FloatField(blank=True, null=True, verbose_name="异常置信度"),
        ),
        migrations.AlterField(
            model_name="alarm",
            name="source_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_detail",
                to="telemetry_app.inspectimage",
                verbose_name="原始底图引用",
            ),
        ),
        migrations.AlterField(
            model_name="alarmdashboardstats",
            name="metric",
            field=models.CharField(
                choices=[
                    ("detect_type", "告警统计"),
                    ("handle_rate", "巡检故障处理率"),
                    ("detect_level2", "二级异常统计"),
                    ("detect_level3", "三级异常统计"),
                ],
                max_length=20,
                verbose_name="统计类型",
            ),
        ),
        migrations.AddConstraint(
            model_name="alarm",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("finding_id__isnull", False), ("source_image__isnull", False)
                ),
                fields=("source_image", "finding_id"),
                name="uniq_alarm_source_image_finding_id",
            ),
        ),
    ]
