# Generated by Django 5.2.7 on 2026-03-16 14:35

import django.db.models.deletion
from django.db import migrations, models


def dedupe_alarm_source_image(apps, schema_editor):
    Alarm = apps.get_model("telemetry_app", "Alarm")
    duplicate_source_ids = (
        Alarm.objects.exclude(source_image_id__isnull=True)
        .values_list("source_image_id", flat=True)
    )
    seen = set()
    for source_id in duplicate_source_ids:
        if source_id in seen:
            continue
        seen.add(source_id)
        alarms = list(
            Alarm.objects.filter(source_image_id=source_id).order_by("id")
        )
        if len(alarms) <= 1:
            continue
        keep_alarm = alarms[-1]
        for alarm in alarms:
            if alarm.id != keep_alarm.id:
                alarm.source_image_id = None
                alarm.save(update_fields=["source_image"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "telemetry_app",
            "0037_alarm_finding_id_alarm_level1_code_alarm_level2_code_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="alarm",
            name="uniq_alarm_source_image_finding_id",
        ),
        migrations.RemoveField(
            model_name="alarm",
            name="finding_id",
        ),
        migrations.RemoveField(
            model_name="alarm",
            name="level1_code",
        ),
        migrations.RemoveField(
            model_name="alarm",
            name="level2_code",
        ),
        migrations.RemoveField(
            model_name="alarm",
            name="level3_code",
        ),
        migrations.RemoveField(
            model_name="alarm",
            name="score",
        ),
        migrations.AddField(
            model_name="alarm",
            name="findings_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="算法findings原始数据"
            ),
        ),
        migrations.RunPython(dedupe_alarm_source_image, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="alarm",
            name="source_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_detail",
                to="telemetry_app.inspectimage",
                verbose_name="原始底图引用",
            ),
        ),
        migrations.AlterField(
            model_name="alarmdashboardstats",
            name="metric",
            field=models.CharField(
                choices=[("detect_type", "告警统计"), ("handle_rate", "巡检故障处理率")],
                max_length=20,
                verbose_name="统计类型",
            ),
        ),
    ]
